### ISSUE TITLE
npm package published with DOS line endings

### ISSUE THREAD

**Issue by dfalling** [jonatanpedersen/git-json-merge#1]
The v.0.3.1 release published on npm uses DOS style line endings.  This makes the bin file fail for me on a Mac:

```
env: node\r: No such file or directory
fatal: Failed to execute internal merge
```

Here are two sources I found useful while troubleshooting this:
- http://foldingair.blogspot.com/2013/05/developing-node-modules-npm-and-git-how.html
- https://github.com/npm/npm/issues/2097

After I manually changed the line endings this project worked great.  Thanks!

**Comment by jonatanpedersen** [comment]
Thank you for your contribution. I ran the dos2unix util and then published a new version (0.3.2) to npm. Hopefully that will have solved the problem.

Cheers!

**Comment by jonatanpedersen** [comment]
Ok, it didn't work, had to try a few more things. But now it installs fine on linux. I ended up publishing from a linux machine. I also fixed a bug where the arguments to xdiff.diff3 were in the wrong order. So it would prefer theirs over ours, which was the opposite of what I wanted :)

**Comment by dfalling** [comment]
Thanks for the really quick turnaround!  I confirmed this works in my environment.

**Comment by james-siteclick** [comment]
Hi, I still have this issue on Mac, package version is 0.4.4 from npm
